
package samples;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * A collection of samples
 * (Generated with springmvc-raml-parser v.0.6.1)
 * 
 */
@RestController
@RequestMapping(value = "sample/samples", produces = "application/json")
public class SampleController {


    /**
     * Retrieves samples
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.GET)
    public List<samples.model.Sample> getSamples() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Creates a sample
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.POST)
    public ResponseEntity createSample(
        @RequestBody
        samples.model.Sample sample) {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Retrieves a given sample by its identifier.
     * 
     */
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public samples.model.Sample getSampleById(
        @PathVariable
        String id) {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

}
